// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr4eA9yeZjcw4YqkfNSvZjaT8--QMJAUE',
    appId: '1:219331369134:web:0cdfdbd4fb01d5e4d0753f',
    messagingSenderId: '219331369134',
    projectId: 'flutter-tmz',
    authDomain: 'flutter-tmz.firebaseapp.com',
    storageBucket: 'flutter-tmz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApri1IIWgRP0osW9V1AIDoHyJT3_UkX5U',
    appId: '1:219331369134:android:71081156ecfa89d8d0753f',
    messagingSenderId: '219331369134',
    projectId: 'flutter-tmz',
    storageBucket: 'flutter-tmz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb77w2VBeHPLSJMo9tfdRwh5dOccyuSvw',
    appId: '1:219331369134:ios:f1f65730cf932e8dd0753f',
    messagingSenderId: '219331369134',
    projectId: 'flutter-tmz',
    storageBucket: 'flutter-tmz.appspot.com',
    iosBundleId: 'com.example.acilTemizlik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb77w2VBeHPLSJMo9tfdRwh5dOccyuSvw',
    appId: '1:219331369134:ios:f1f65730cf932e8dd0753f',
    messagingSenderId: '219331369134',
    projectId: 'flutter-tmz',
    storageBucket: 'flutter-tmz.appspot.com',
    iosBundleId: 'com.example.acilTemizlik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr4eA9yeZjcw4YqkfNSvZjaT8--QMJAUE',
    appId: '1:219331369134:web:203fd576bcff91e8d0753f',
    messagingSenderId: '219331369134',
    projectId: 'flutter-tmz',
    authDomain: 'flutter-tmz.firebaseapp.com',
    storageBucket: 'flutter-tmz.appspot.com',
  );

}